### ISSUE TITLE
Video is Late

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/HardWonKnowledge#38]

**Comment by JWHDempsey** [comment]
Video has been posted here:

http://www.youtube.com/watch?v=Od7eXYPamQA&feature=youtu.be

**Comment by josemvidal** [comment]
Got it. That is a Most Awesome Video.

On Wed, Apr 23, 2014 at 5:09 AM, JWHDempsey notifications@github.comwrote:

> Video has been posted here:
> 
> http://www.youtube.com/watch?v=Od7eXYPamQA&feature=youtu.be
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/SCCapstone/HardWonKnowledge/issues/38#issuecomment-41139771
> .

## 

Jose M Vidal, Undergraduate Director, Computer Science and Engineering
http://jmvidal.cse.sc.edu
